---
title: "Lecture 1"
subtitle: "Intro, math and micro review"
author: Ivan Rudik
date: AEM 6510
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'


---
exclude: true

```{r xaringanExtra, echo = FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "editable", "panelset", "webcam"))
```


---

# AEM 6510: Environmental and resource economics

Welcome to AEM 6510

**Instructor:** Ivan Rudik

**Synchronous class time:** Tuesday and Thursday

**Zoom office hours:**

**Textbook:** A Course in Environmental Economics by Phaneuf and Requate

**Prerequisites:** MATH 1110 or equivalent. 


---

# What's the point of the course?

To learn:

Core environmental theory

--

Theory of regulation

--

Applied welfare analysis

--

How to do empirical analysis on the environment

--

How to use R and do geospatial analysis
- This is increasingly important in environmental economics


---

# What do you need for this class?

Attend lectures if possible

Do your homework and takehome prelims

---

# Here's how you'll be graded

Prelims: 30% and 20% (one theory, one empirical)   
Problem sets: 25%  
Literature review paper: 20%  
Literature review presentation: 5%

A: 92-100; A-: 90-91  
B+: 88-89; B: 82-87; B-: 80-81  
C+: 78-79; C: 72-77; C-: 70-71  
D+: 68-69; D: 62-67; D-: 60-61  
F: < 60 


---

# Prelims

There are two, one on theory and one on empirical methods

Your highest-scoring prelim is 30% of your grade,  
your lowest-scoring prelim is 20%

Prelims will basically just be longer homeworks that you are expected to complete .hi-red[on your own]

Prelims are due at the listed time and can be submitted on Canvas

Late prelims automatically get 30% deducted

If a prelim is more than 24 hours late it will be assigned 0%


---

# Problem sets

There will be 4 problem sets

Your highest scoring problem set is worth 10%, the rest are worth 5%

---

# Final project

There is a final project for the course aimed toward getting you moving toward your M exam

You can choose one of two options:

1) Literature Review

2) Data dive

---

# Final project: lit review

Write a literature review on 5-10 papers all in a particular subfield of environmental and resource economics
  - What are the findings? Common threads? Work yet to be done?
  - You'll need to run the papers by me before committing

Present your literature review to the class

More details later

---

# Final project: data dive

Find a new data set that we will not use in class but is useful for environmental economics
  - What are the data? How do you get them? How do you use them? What makes them relevant for economics?
  - You'll need to run it by me
  
Do some preliminary analyses on the data

Present the dataset to the class

More details later

---

# Course schedule: Theory

1. Micro & math recap, theory of externalities
2. Environmental problems and policy issues
3. Intro to the theory of environmental policy
4. Intro to the theory of environmental policy
5. Imperfect information
6. Competitive output markets
7. Non-competitive output markets
8. Pre-existing distortions
9. Cap and trade
10. Theory of applied welfare economics
11. Theory of applied welfare economics
12. Revealed preference models

---

# Course schedule: Empirics

13. R and the tidyverse, causal inference
14. R and the tidyverse, causal inference
15. Environmental health, difference-in-differences, and event studies
16. Environmental health, difference-in-differences, and event studies
17. Hedonics and regression discontinuity
18. Hedonics and regression discontinuity
19. Climate change background
20. Climate change and the Ricardian model
21. Climate change and two-way fixed effects
22. Deforestation, remote sensing, and simple features
23. Deforestation, remote sensing, and simple features
24. Perverse incentives, remote sensing, and simple features


---

# Part 1: Math and micro review